<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>有链磁力资源网 MAGNET.URLNK.COM</title>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    </head>
    <body>
        <h4><a href="http://www.urlnk.com">有链</a> &gt; <a href="./">MAGNET</a> (本站不对文件内容和安全负责，仅提供 magnet 链接检索)</h4>
        <h1><img src="img/favicon.48x48.png"/> 有链 Magnet 磁力链接资源网</h1>

        <blockquote>
            <form action="search">
                <input name="q" value="" style="width:300px;"  />
                <button type="submit">&crarr;</button>
                <a href="search?q=yyets">yyets</a> <a href="search?q=%E5%AD%A3">季</a> <a href="search?q=hd">hd</a> <a href="search?q=dvd">dvd</a> 
<a href="search?q=264">264</a>
            </form>
             <p><?=$min+1?> - <?=$min+$count?> / 共 <?=$total?></p>
            <ul>
<?php
foreach ($all as $r) {
?>
<li><a href="entry/<?=$r->id?>.html"><?=$r->title?></a></li>
<?php
}
?>                
            </ul>
             <a href="index?page=<?=$page?>"><?=$page?></a>  / 共 <a href="index?page=<?=$pages?>"><?=$pages?></a>  页
                <? if(0<$prevPage){ ?><a href="index?page=<?=$prevPage?>">上一页</a> <? } ?>
                <? if($pages>=$nextPage){ ?><a href="index?page=<?=$nextPage?>">下一页</a><? } ?>
                </blockquote>
<?php
        include_once '../application/views/scripts/footer.phtml';
?>
    </body>
</html>
