<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Page not found - 有链 magnet 资源网</title>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    </head>
    <body>
        <h4><a href="http://www.urlnk.com">有链</a> &gt; <a href="../">MAGNET</a> &gt; ERROR 404</h4>

        <h1>Page not found</h1>
<?php
        include_once '../application/views/scripts/footer.phtml';
        ?>
    </body>
</html>
