<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>有链磁力链接资源搜索 MAGNET.URLNK.COM</title>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    </head>
    <body>
        <h4><a href="http://www.urlnk.com">有链</a> &gt; <a href="./">MAGNET</a> &gt; 搜索 <?=$q?></h4>
        <h1>有链 Magnet 资源搜索</h1>

        <blockquote>
            <form action="">
                <input name="q" value="<?=$text?>" style="width:500px;" />
                <button type="submit">&crarr;</button>
            </form>
            <ul>
<?php
foreach ($all2 as $r) {
    $dn=$r->hash;
    if($r->dn){
        $dn=$r->dn;
    }
?>
<li><a href="<?=$typeIds[$r->type]?>/<?=$r->hash?>"><?=$dn?></a></li>
<?php
}
?>                
            </ul>
<?php
        include_once '../application/views/scripts/footer.phtml';
?>
    </body>
</html>
